version: "3.9"
services:
  reverseproxy:
      build:
        context: ./quick-start
        dockerfile: ./Dockerfile.reverseproxy
      ports:
          - 3333:3333
          - 9000:9000
      restart: always
      depends_on:
        - paima-engine
        - frontend
  postgres:
    image: postgres:14
    container_name: chess-2-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - chess-2-db:/var/lib/postgresql/data
      - ./db/migrations/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      # Use pg_isready to check postgres is running. Substitute different
      # user `postgres` if you've setup differently to config/pgpass-mainnet
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5432"]
      interval: 20s
      timeout: 5s
      retries: 5
  paima-engine:
    depends_on:
      - postgres
    build:
      context: ../
      dockerfile: ./chess/quick-start/Dockerfile.engine
    restart: always
  frontend:
    build:
      context: ../
      dockerfile: ./chess/quick-start/Dockerfile.frontend

volumes:
  chess-2-db:
